### ISSUE TITLE
Why Twice once is enough Please change

### ISSUE THREAD

**Issue by Sina30** [swkeep/keep-bags#20]
I think what you're doing is really good, but it doesn't have to be. And why is so much blocked? As a dev, you should have access to everything in your keep-harmony. Why twice is enough, please change

[ script:keep-harmony] ═══════════════════════════[ Database Check ]═══════════════════════════
[ script:keep-harmony] ------------------------------------------------------------------------
[ script:keep-harmony] 		░██████╗░██╗░░░░░░░██╗██╗░░██╗███████╗███████╗██████╗░
[ script:keep-harmony] 		██╔════╝░██║░░██╗░░██║██║░██╔╝██╔════╝██╔════╝██╔══██╗
[ script:keep-harmony] 		╚█████╗░░╚██╗████╗██╔╝█████═╝░█████╗░░█████╗░░██████╔╝
[ script:keep-harmony] 		░╚═══██╗░░████╔═████║░██╔═██╗░██╔══╝░░██╔══╝░░██╔═══╝░
[ script:keep-harmony] 		██████╔╝░░╚██╔╝░╚██╔╝░██║░╚██╗███████╗███████╗██║░░░░░
[ script:keep-harmony] 		╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░░░░
[ script:keep-harmony] ------------------------------------------------------------------------
[ script:keep-harmony]                 Discord > https://discord.gg/ccMArCwrPV                 
[ script:keep-harmony]                    GitHub > https://github.com/swkeep                   
[ script:keep-harmony]                     Tebex > https://swkeep.tebex.io                     
[ script:keep-harmony]                      Resource > [keep-harmony]                     
[ script:keep-harmony] ------------------------------------------------------------------------

**Comment by swkeep** [comment]
Well, even with the access you have, you didn't try to remove it because that part is straightforward to remove.

Here is the link to the code for reference: [server_main.lua](https://github.com/swkeep/keep-bags/blob/07c8c1a3d2efa8de6d83979b6faed0bae6d22b47/server/server_main.lua#L280)

`And why is so much blocked?` It's not the right wording for it `Why is so much encrypted?` That is the correct term.
The answer is that I never developed it to be an open-source script and it will stay that way.

**Comment by Sina30** [comment]
I didn't look there because it doesn't work for us, we only have error messages Legacy 1.8.5, then we fixed it again because of all the errors that come he gives me the backpacks and everything but I want to use them, e.g. the briefcase should be yes a pin come what he does not made your config from the docs as we need but nothing just errors
